<?php
/**
 * Shows Picasa Web Albums on a page
 */

/**
 * Implements hook_help().
 */
function vih_pwi_help($path, $arg) {
  global $base_path;
  switch ($path) {
    case 'admin/help#vih_pwi':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PWI embeds Picasa Webalbum on your site') .'</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Usage') . '</dt>';
      $output .= '<dd>' . t('To embed the Picasa Webalbums, you add the the block from the <a href="@pwi">blocks configuration page</a>.', array('@pwi' => $base_path . 'admin/structure/block')) . '. '.t('Remember to configure the block').'</dd>';
      $output .= '</dl>';
      return $output;
    case 'admin/settings/pwi':
      $output = t('Configure your PWI implementation of Picasa Webalbums');
      return $output;
  }
}

function vih_pwi_block_info() {
  $blocks['vih_pwi'] = array(
    'info' => t('Picasa Webalbums'), 
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}

function vih_pwi_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'vih_pwi':
      $block['subject'] = '';
      $block['content'] = vih_pwi_view();
      break;
  }
  return $block;
}

/**
 * @todo Write validator handler
 */
function vih_pwi_block_configure($delta = '') {
  $form = array();
  if ($delta == 'vih_pwi') {
    $form['vih_pwi'] = array(
      '#type' => 'fieldset',
      '#title' => t('Settings for Picasa Webalbum block'),
      '#tree' => TRUE,
    );
    $form['vih_pwi']['vih_pwi_picasa_user'] = array(
      '#type' => 'textfield',
      '#title' => t('Picasa User'),
      '#required' => true,
      '#default_value' => variable_get('vih_pwi_picasa_user', ''),
    ); 
    // @todo create a select box with available sizes
    $form['vih_pwi']['vih_pwi_thumbsize'] = array(
      '#type' => 'textfield',
      '#title' => t('Thumbnail size'),
      '#required' => true,
      '#default_value' => variable_get('vih_pwi_thumbsize', 160),
    ); 
    $form['vih_pwi']['vih_pwi_max_results'] = array(
      '#type' => 'textfield',
      '#title' => t('Max results'),
      '#required' => true,
      '#default_value' => variable_get('vih_pwi_max_results', 12),
    ); 
  }
  return $form;
}

function vih_pwi_block_save($delta = '', $edit = array()) {
  if ($delta == 'vih_pwi') {
    variable_set('vih_pwi_picasa_user', $edit['vih_pwi']['vih_pwi_picasa_user']);
    variable_set('vih_pwi_thumbsize', $edit['vih_pwi']['vih_pwi_thumbsize']);
    variable_set('vih_pwi_max_results', $edit['vih_pwi']['vih_pwi_max_results']);        
  }
}

/**
 * Implementation of hook_views_api().
 */
function vih_pwi_view() {
    if (variable_get('vih_pwi_picasa_user', '') == '') {
      drupal_set_message(t('Picasa user has not been set, so the block cannot be shown'), 'error');
    } 
    
    drupal_add_css(libraries_get_path('jquery.pwi') . '/css/pwi.css');
    drupal_add_js(libraries_get_path('jquery.pwi') . '/js/jquery.pwi.js');
    drupal_add_js('
(function ($) {
    $(document).ready(function() {
        $("#picasaweb").pwi({
            username: \''.check_plain(variable_get('vih_pwi_picasa_user')).'\',
            maxResults: '.check_plain(variable_get('vih_pwi_max_results', 12)).',
            showAlbumDescription: false,
            showPhotoCaption: false,
            photoCaptionLength: 5,
            thumbSize: '.check_plain(variable_get('vih_pwi_thumbsize', 160)).',
            thumbCrop: 1,
            showPhotoDate: false,
            showSlideshowLink: true,
            labels: {photo:"'.t('photo').'",	//-- override labels, to translate into your required language
                     photos: "'.t('photos').'",
                     albums: "'.t('Back to albums').'",
                     slideshow: "'.t('Show slideshow').'",
                     loading: "'.t('Fetching pictures').'",
                     page: "'.t('Page').'",
                     prev: "'.t('Previous').'",
                     next: "'.t('Next').'",
                     devider: "|"
            },
            months: ["'.t('January').'","'.t('February').'","'.t('March').'","'.t('April').'","'.t('May').'","'.t('June').'","'.t('July').'","'.t('August').'","'.t('September').'","'.t('October').'","'.t('November').'","'.t('December').'"]
        });
    });
})(jQuery);', 'inline');
    return '<div id="picasaweb"></div>';
}
