<?php
/**
 * Shows Picasa Web Albums on a page
 */

/**
 * Implements hook_help().
 */
function vih_pwi_help($path, $arg) {
  global $base_path;
  switch ($path) {
    case 'admin/help#vih_pwi':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PWI embeds Picasa Webalbum on your site') .'</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Usage') . '</dt>';
      $output .= '<dd>' . t('To embed the Picasa Webalbums, you add the the block from the <a href="@pwi">blocks configuration page</a>.', array('@pwi' => $base_path . 'admin/structure/block')) . '. '.t('Remember to configure the block').'</dd>';
      $output .= '</dl>';
      return $output;
    case 'admin/settings/pwi':
      $output = t('Configure your PWI implementation of Picasa Webalbums');
      return $output;
  }
}

/**
 * Implements hook_libraries_info();
 */
function vih_pwi_libraries_info() {
  $libraries['jquery.pwi'] = array(
    'name' => 'PWI',
    'vendor url' => 'https://code.google.com/p/pwi/',
    'download url' => 'https://code.google.com/p/pwi/downloads/list',
    'version arguments' => array(
      'file' => 'js/jquery.pwi.js',
      'pattern' => '/\@revision ((\d+)\.(\d+)\.(\d+))/',
    ),
    'files' => array(
      'js' => array(
        'js/jquery.pwi.js',
      ),
      'css' => array(
        'css/pwi.css',
      ),
    ),
    // Optional: Register files to auto-load for your module. All files must be
    // keyed by module, and follow the syntax of the 'files' property.
    'integration files' => array(
      'vih_pwi' => array(
        'css' => array('css/pwi.css'),
        'js' => array('js/jquery.pwi.js'),
      ),
    ),
  );
  return $libraries;
}

/**
 * Check if the PWI library has been loaded, and warn if missing.
 *
 * @return bool
 *   A boolean indicating the Neat Scrollbar loaded status.
 */
function pwi_loaded() {
  if (($library = libraries_load('jquery.pwi')) && !empty($library['loaded'])) {
    return TRUE;
  }
  elseif (user_access('administer permissions')) {
    // Alert the authorized user/administrator to the abscence of the library.
    drupal_set_message(t('The PWI Library could not be found.
      Please check the installation instructions and the <a href="@status">Status Report</a>.',
      array('@status' => url('admin/reports/status'))), 'warning');
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function vih_pwi_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_block_info().
 */
function vih_pwi_block_info() {
  $blocks['vih_pwi'] = array(
    'info' => t('Picasa Webalbums'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function vih_pwi_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'vih_pwi':
      $block['subject'] = '';
      $block['content'] = _vih_pwi_write_this_blok();
      break;
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 * @todo Write validator handler
 */
function vih_pwi_block_configure($delta = '') {
  $form = array();
  if ($delta == 'vih_pwi') {
    $form['vih_pwi'] = array(
      '#type' => 'fieldset',
      '#title' => t('Settings for Picasa Webalbum block'),
      '#tree' => TRUE,
    );
    $form['vih_pwi']['vih_pwi_picasa_user'] = array(
      '#type' => 'textfield',
      '#title' => t('Picasa User'),
      '#required' => true,
      '#default_value' => variable_get('vih_pwi_picasa_user', ''),
    );
    // @todo create a select box with available sizes
    $form['vih_pwi']['vih_pwi_thumbsize'] = array(
      '#type' => 'textfield',
      '#title' => t('Thumbnail size'),
      '#required' => true,
      '#default_value' => variable_get('vih_pwi_thumbsize', 160),
    );
    $form['vih_pwi']['vih_pwi_max_results'] = array(
      '#type' => 'textfield',
      '#title' => t('Max results'),
      '#required' => true,
      '#default_value' => variable_get('vih_pwi_max_results', 12),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function vih_pwi_block_save($delta = '', $edit = array()) {
  if ($delta == 'vih_pwi') {
    variable_set('vih_pwi_picasa_user', $edit['vih_pwi']['vih_pwi_picasa_user']);
    variable_set('vih_pwi_thumbsize', $edit['vih_pwi']['vih_pwi_thumbsize']);
    variable_set('vih_pwi_max_results', $edit['vih_pwi']['vih_pwi_max_results']);
  }
}

/**
 * Implementation of hook_views_api().
 */
function _vih_pwi_write_this_blok() {
  if (!pwi_loaded()) {
    return;
  }

  drupal_add_js('
(function ($) {
  $(document).ready(function() {
    $("#picasaweb").pwi({
      username: \''.check_plain(variable_get('vih_pwi_picasa_user')).'\',
      maxResults: '.check_plain(variable_get('vih_pwi_max_results', 12)).',
      showAlbumDescription: false,
      showPhotoCaption: false,
      photoCaptionLength: 5,
      thumbSize: '.check_plain(variable_get('vih_pwi_thumbsize', 160)).',
      thumbCrop: 1,
      showPhotoDate: false,
      showSlideshowLink: true,
      labels: {photo:"'.t('photo').'",	//-- override labels, to translate into your required language
        photos: "'.t('photos').'",
        albums: "'.t('Back to albums').'",
        slideshow: "'.t('Show slideshow').'",
        loading: "'.t('Fetching pictures').'",
        page: "'.t('Page').'",
        prev: "'.t('Previous').'",
        next: "'.t('Next').'",
        devider: "|"
      },
      months: ["'.t('January').'","'.t('February').'","'.t('March').'","'.t('April').'","'.t('May').'","'.t('June').'","'.t('July').'","'.t('August').'","'.t('September').'","'.t('October').'","'.t('November').'","'.t('December').'"]
    });
  });
})(jQuery);', 'inline');
  return '<div id="picasaweb"></div>';
}
